
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: ubuntu:16.04

# https://docs.gitlab.com/ee/ci/caching/
# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - .venv/

#commands to run in the Docker container before starting each job.
before_script:
  - apt-get -qq update
  - apt-get -qq install python3-venv    # needed to create venv
  - python3 -m venv .venv
  - source .venv/bin/activate
  - python -V                           # Print for debugging. It should be 3.5
  - pip install --upgrade pip
  - pip install -U -r requirements/base.txt
  - pip install -U -r requirements/development.txt

# Stages
stages:
  - Static Analysis
  - Test

# Jobs
PEP8, lint Python files with flake8:
  stage: Static Analysis
  script:
    - flake8 production/schools_l3vpn_site_add.py

Test, pretend we do:
  stage: Test
  script:
    - flake8 production/schools_l3vpn_site_add.py
