
# https://stackoverflow.com/questions/50333650/install-python-package-in-docker-file

# Pull base image.
FROM ubuntu:16.04

# LABEL about the custom image
LABEL maintainer="daniel.lete@heanet.ie"
LABEL version="2020-12-18"
LABEL description="This is custom Docker image \
with Ubuntu 16.04, python 3.5 and requests."

# jump into a tmp directory so that we can install some dependencies
# https://www.integralist.co.uk/posts/dev-environments-within-docker-containers/
WORKDIR /tmp

RUN apt-get update && apt-get install -y \
    git \
    htop \
    python3-pip \
    vim \
    # Official Debian and Ubuntu images automatically run apt-get clean, so 
    # explicit invocation is not required.
    # apt-get clean && \
    && rm -rf /var/lib/apt/lists/*

# Install pip requirements
ADD requirements/* ./
RUN python3 -m pip install --upgrade pip \
    && python3 -m pip install -r base.txt \
    && python3 -m pip install -r development.txt

# Define working directory.
WORKDIR /app

# Switching to a non-root user, please refer to https://aka.ms/vscode-docker-python-user-rights
RUN useradd appuser \
    && chown -R appuser /app
ADD auxiliary_settings/.vimrc /home/appuser/
RUN chown -R appuser /home/appuser
USER appuser

# Define default command.
CMD ["bash"]